# Generated by Django 5.2 on 2025-06-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_fileupload_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
