# Generated by Django 5.2 on 2025-06-07 06:47

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=portal.models.UploadToUserFolderWithConflictResolution()),
        ),
    ]
